Fixed the npm run in the github action

diff --git a/.github/workflows/deploy-dev.yml b/.github/workflows/deploy-dev.yml
--- a/.github/workflows/deploy-dev.yml
+++ b/.github/workflows/deploy-dev.yml
@@ -28,7 +28,7 @@ jobs:
             echo "Resetting to origin/devel..."
             git reset --hard origin/devel || { echo "Git reset failed"; exit 1; }
             echo "Installing dependencies..."
-            npm ci || { echo "npm ci failed"; exit 1; }
+            npm ci --legacy-peer-deps || { echo "npm ci failed"; exit 1; }
             echo "Building app..."
             npm run build || { echo "Build failed"; exit 1; }
             echo "Restarting app wtih PM2..."
